<%@ Page Title="" Language="C#" MasterPageFile="~/SiteMaster2.master" AutoEventWireup="true" CodeFile="MyPayStubs.aspx.cs" Inherits="My_MyPayStubs" %>
<%@ Register Assembly="Microsoft.ReportViewer.WebForms, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" Namespace="Microsoft.Reporting.WebForms" TagPrefix="rsweb" %>


<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" Runat="Server">
    <style>
        .TableRowCss {
            border: none;
        }
        
        .SearchBtnCSS {
            font-size: 1.3em;
            font-weight: bold;
            color: red;
            width: 100%;
        }        
        
        .ClearBtnCss {
            font-size: 1.3em;
            font-weight: bold;
            color: red;
            width: 100%;
            float: right;
        }     
        
        .ItalicCss {
            font-style: italic;
            font-size: .85em;
            color: grey;
        }           
    </style>   
    
    <script type="text/javascript">

        // Reset Form After 5 Minutes 
        // Don't Leave Info Showing On Screen
        $(document).ready(function() {
            var timer, delay = 600000; //5 minutes counted in milliseconds.
            timer = setInterval(function () {
                $('#BtnClearRpt').trigger('click');
            }, delay);
        });
    </script> 
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" Runat="Server">
    

<!----------------->
<!-- Form Header -->
<!----------------->           
    <div class="ui-widget-header ui-corner-all"  >
        <div  style="text-align: center; font-size: 2em;">Your Pay Stubs</div>
    </div>
    
            <div style="float: left; width: 300px; background-color: white;">
                <asp:Button ID="BtnClearRpt" runat="server" OnClick="ClearRpt_Clicked"  CssClass="SearchBtnCSS" Text="Clear Report"/>                             
                <asp:GridView ID="gvPayStubs" runat="server" CssClass="GridCenterCss"
                    
                    AutoGenerateColumns="False" 
                    AutoGenerateSelectButton="False" 
                    AutoGenerateEditButton="false"
                    AutoGenerateDeleteButton="False"
                     
                    AllowSorting="False"
                    AllowPaging="True" 

                    ShowFooter="False"
                    
                    PageSize="90" 
                    CellPadding="2" 
                    CellSpacing="2" 

                    BorderStyle="None"
                    
                    OnRowDataBound="gvPayStubs_RowDataBound"
                    OnPageIndexChanging="gvPayStubs_PageIndexChanging" 
                 >
                                    
                    <RowStyle CssClass="TableRowCss"></RowStyle>
                    

                    <Columns>
                        
                        <%-- Posting Date --%>
                        <asp:TemplateField HeaderStyle-BorderStyle="None" HeaderText="Payroll Date" >
                            <HeaderStyle BorderStyle="None" />
                            <ItemStyle CssClass="TableRowCss" />

                            <ItemTemplate>
                                <asp:Label ID="lblPostingDate" runat="server" ></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        

                      

                        <%-- Password To Run  --%>
                        <asp:TemplateField HeaderStyle-BorderStyle="None" HeaderText="Enter Password To View" HeaderStyle-CssClass="ItalicCss">
                            <HeaderStyle BorderStyle="None" />
                            <ItemStyle CssClass="TableRowCss" />
                            
                            
                            <ItemTemplate>
                                <asp:TextBox ID="txtRunPwd" runat="server" CssClass="DataInputCss"  OnTextChanged="Gv1PasswordEntered" AutoPostBack="True" TextMode="Password" />
                            </ItemTemplate>

                        </asp:TemplateField>
                        

                    </Columns>

                    <PagerStyle HorizontalAlign="Left"/>
                </asp:GridView>
  
           </div>
           
           <div style="float: left; background-color: gainsboro; width: auto; height: 800px;">
                <rsweb:ReportViewer ID="MyReportViewer" runat="server" Width="590" Height="100%" ProcessingMode="Remote" Style="display: table !important; margin: 0; overflow: auto !important;">
                </rsweb:ReportViewer>               
           </div>
           
            <div style="float: left; width: 300px; background-color: white;">
                                            
                <asp:GridView ID="gvPayStubs2" runat="server" CssClass="GridCenterCss"
                    
                    AutoGenerateColumns="False" 
                    AutoGenerateSelectButton="False" 
                    AutoGenerateEditButton="false"
                    AutoGenerateDeleteButton="False"
                     
                    AllowSorting="False"
                    AllowPaging="True" 

                    ShowFooter="False"
                    
                    PageSize="90" 
                    CellPadding="2" 
                    CellSpacing="2" 

                    BorderStyle="None"
                    
                    OnRowDataBound="gvPayStubs_RowDataBound"
                    OnPageIndexChanging="gvPayStubs_PageIndexChanging" 
                 >
                                    
                    <RowStyle CssClass="TableRowCss"></RowStyle>
                    

                    <Columns>
                        
                        <%-- Posting Date --%>
                        <asp:TemplateField HeaderStyle-BorderStyle="None" HeaderText="Payroll Date" >
                            <HeaderStyle BorderStyle="None" />
                            <ItemStyle CssClass="TableRowCss" />

                            <ItemTemplate>
                                <asp:Label ID="lblPostingDate" runat="server" ></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        

                      

                        <%-- Password To Run  --%>
                        <asp:TemplateField HeaderStyle-BorderStyle="None" HeaderText="Enter Password To View"  HeaderStyle-CssClass="ItalicCss">
                            <HeaderStyle BorderStyle="None" />
                            <ItemStyle CssClass="TableRowCss" />
                            
                            
                            <ItemTemplate>
                                <asp:TextBox ID="txtRunPwd" runat="server" CssClass="DataInputCss"  OnTextChanged="Gv2PasswordEntered" AutoPostBack="True" TextMode="Password" />
                            </ItemTemplate>

                        </asp:TemplateField>
                        

                    </Columns>

                    <PagerStyle HorizontalAlign="Left"/>
                </asp:GridView>
  
           </div>

</asp:Content>

