using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Reflection;
using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Spreadsheet;

using SpreadsheetLight;
using SpreadsheetLight.Charts;

public partial class Safety_Incident_Spreadsheet : System.Web.UI.Page
{
    protected void Page_Load(object sender, EventArgs e)
    {

    }

    protected void btn_SSL_Click(object sender, EventArgs e)
    {
        int rowCount;

        //////////////////////////////////
        // Build The Document Framework //
        //////////////////////////////////
        SLDocument sl = new SLDocument
        {
            DocumentProperties =
            {
                Creator = "Larry Truitt",
                ContentStatus = "Generated " + DateTime.Now,
                Title = "Incident and Accident Tracking",
                Description = "Incident and Accident tracking report generated by SiYOU.Shermco.Com"
            }
        };

        //////////////////////
        // Setup The Sheets //
        //////////////////////
        sl.RenameWorksheet(SLDocument.DefaultFirstSheetName, "Incident Log");
        sl.AddWorksheet("Consolidated Summary");
        sl.AddWorksheet("Master Summary");
        sl.AddWorksheet("January");

        ///////////////////////////////////////////
        // Build The Incident Accident Worksheet //
        ///////////////////////////////////////////
        sl.SelectWorksheet("Incident Log");
        rowCount = BuildIAData(ref sl);
        BuildIAHeader(ref sl, rowCount);
        

        ///////////////////////////////////////////
        // Build The Incident Accident Worksheet //
        ///////////////////////////////////////////
        sl.SelectWorksheet("Consolidated Summary");
        BuildSumHeader(ref sl, rowCount);

        ///////////////////////////////////////////
        // Build The Incident Accident Worksheet //
        ///////////////////////////////////////////
        sl.SelectWorksheet("Master Summary");
        BuildSumHeader(ref sl, rowCount);

        ///////////////////////////////////////////
        // Build The Incident Accident Worksheet //
        ///////////////////////////////////////////
        sl.SelectWorksheet("January");
        BuildSumHeader(ref sl, rowCount);



        //SLComment comm;
        //comm = sl.CreateComment();
        //comm.SetText("first!!111!1!!1!!");
        //sl.InsertComment(1, 1, comm);

        sl.SelectWorksheet("Incident Log");

        Response.Clear();
        Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
        Response.AddHeader("Content-Disposition", "attachment; filename=WebStreamDownload.xlsx");
        sl.SaveAs(Response.OutputStream);
        Response.End();

    }

    private void BuildIAHeader(ref SLDocument sl, int rowCount)
    {
        rowCount += 2;

        SLStyle styleHeaderA1 = sl.CreateStyle();
        styleHeaderA1.SetWrapText(true);
        styleHeaderA1.Font.FontName = "Arial";
        styleHeaderA1.Font.FontSize = 11;
        styleHeaderA1.Font.FontColor = System.Drawing.Color.Blue;
        styleHeaderA1.Alignment.Horizontal = HorizontalAlignmentValues.Center;
        styleHeaderA1.Alignment.Vertical = VerticalAlignmentValues.Bottom;

        sl.SetCellStyle("A1", "AG2", styleHeaderA1);

        sl.SetRowHeight(1, 30);
        sl.SetRowHeight(2, 57);

        sl.SetColumnWidth("A", 9.43);
        sl.SetColumnWidth("B", 9.43);
        sl.SetColumnWidth("C", 13);
        sl.SetColumnWidth("D", 9.43);
        sl.SetColumnWidth("E", 9.43);
        sl.SetColumnWidth("F", 13);
        sl.SetColumnWidth("G", 13);
        sl.SetColumnWidth("H", 13);
        sl.SetColumnWidth("I", 13);
        sl.SetColumnWidth("J", 11);
        sl.SetColumnWidth("K", 9.43);
        sl.SetColumnWidth("W", 50);
        sl.SetColumnWidth("X", 50);
        sl.SetColumnWidth("Y", 10);
        sl.SetColumnWidth("Z", 50);
        sl.SetColumnWidth("AA", 50);
        sl.SetColumnWidth("AB", 20);
        sl.SetColumnWidth("AC", 50);

        sl.MergeWorksheetCells("A1", "A2");
        sl.MergeWorksheetCells("B1", "B2");
        sl.MergeWorksheetCells("C1", "C2");
        sl.MergeWorksheetCells("D1", "D2");
        sl.MergeWorksheetCells("M1", "M2");
        sl.MergeWorksheetCells("R1", "R2");
        sl.MergeWorksheetCells("V1", "V2");
        sl.MergeWorksheetCells("W1", "W2");
        sl.MergeWorksheetCells("X1", "X2");
        sl.MergeWorksheetCells("Y1", "Y2");
        sl.MergeWorksheetCells("Z1", "Z2");
        sl.MergeWorksheetCells("AA1", "AA2");
        sl.MergeWorksheetCells("AB1", "AB2");
        sl.MergeWorksheetCells("AC1", "AC2");


        sl.MergeWorksheetCells("E1", "G1");
        sl.MergeWorksheetCells("H1", "L1");
        sl.MergeWorksheetCells("N1", "Q1");
        sl.MergeWorksheetCells("S1", "U1");
        sl.MergeWorksheetCells("AD1", "AG1");


        sl.SetCellValue("A1", "Shermco Number");
        sl.SetCellValue("B1", "Claim Number");
        sl.SetCellValue("C1", "Date of Occurance");
        sl.SetCellValue("D1", "Open Closed");

        sl.SetCellValue("E1", "Type of Incident");
        sl.SetCellValue("E2", "Type");
        sl.SetCellValue("F2", "Description");
        sl.SetCellValue("G2", "Location");

        sl.SetCellValue("H1", "OSHA 300 Log Information");
        sl.SetCellValue("H2", "Medically Recordable");
        sl.SetCellValue("I2", "Restricted Duty");
        sl.SetCellValue("J2", "Number of Restricted Days");
        sl.SetCellValue("K2", "Lost Time");
        sl.SetCellValue("L2", "Number of Lost Time Days");

        sl.SetCellValue("M1", "Drug / Breath Alcohol Test");

        sl.SetCellValue("N1", "Employee");
        sl.SetCellValue("N2", "Dept");
        sl.SetCellValue("O2", "Number");
        sl.SetCellValue("P2", "Last Name");
        sl.SetCellValue("Q2", "First Name");

        sl.SetCellValue("R1", "Unit Number");

        sl.SetCellValue("S1", "Supervisor");
        sl.SetCellValue("S2", "Number");
        sl.SetCellValue("T2", "Last Name");
        sl.SetCellValue("U2", "First Name");

        sl.SetCellValue("V1", "Project Number");
        sl.SetCellValue("W1", "Description of Occurance");
        sl.SetCellValue("X1", "Unsafe Act or Condition");
        sl.SetCellValue("Y1", "Discipline Issued");
        sl.SetCellValue("Z1", "Discipline Description");
        sl.SetCellValue("AA1", "Actions to Prevent ReOccurance");
        sl.SetCellValue("AB1", "Responsible Party");
        sl.SetCellValue("AC1", "Additional Comments");

        sl.SetCellValue("AD1", "Cost");
        sl.SetCellValue("AD2", "In-House");
        sl.SetCellValue("AE2", "Incurred");
        sl.SetCellValue("AF2", "Reserve");
        sl.SetCellValue("AG2", "Total");


        SLStyle styleColumnGroup1 = sl.CreateStyle();
        styleColumnGroup1.Fill.SetPatternType(PatternValues.Solid);
        styleColumnGroup1.Fill.SetPatternForegroundColor(System.Drawing.Color.FromArgb(100, 230, 230, 230));
        sl.SetCellStyle("A1", "D" + rowCount, styleColumnGroup1);
        sl.SetCellStyle("H1", "L" + rowCount, styleColumnGroup1);
        sl.SetCellStyle("N1", "Q" + rowCount, styleColumnGroup1);
        sl.SetCellStyle("S1", "U" + rowCount, styleColumnGroup1);
        sl.SetCellStyle("W1", "W" + rowCount, styleColumnGroup1);
        sl.SetCellStyle("Y1", "Z" + rowCount, styleColumnGroup1);
        sl.SetCellStyle("AC1", "AC" + rowCount, styleColumnGroup1);

        //SLStyle styleColumnGroup2 = sl.CreateStyle();
        //styleColumnGroup2.Fill.SetPatternType(PatternValues.Solid);
        //styleColumnGroup2.Fill.SetPatternForegroundColor(System.Drawing.Color.LightGray);
        //sl.SetCellStyle("E1", "G99", styleColumnGroup2);
        //sl.SetCellStyle("M1", "M99", styleColumnGroup2);
        //sl.SetCellStyle("R1", "R99", styleColumnGroup2);
        //sl.SetCellStyle("V1", "V99", styleColumnGroup2);
        //sl.SetCellStyle("X1", "X99", styleColumnGroup2);
        //sl.SetCellStyle("AA1", "AB99", styleColumnGroup2);
        //sl.SetCellStyle("AD1", "AG99", styleColumnGroup2);



        SLStyle borderAllCell = sl.CreateStyle();
        borderAllCell.Border.RightBorder.BorderStyle = BorderStyleValues.Thin;
        borderAllCell.Border.BottomBorder.BorderStyle = BorderStyleValues.Thin;
        borderAllCell.Border.RightBorder.Color = System.Drawing.Color.FromArgb(100, 192, 192, 192);
        borderAllCell.Border.BottomBorder.Color = System.Drawing.Color.FromArgb(100, 192, 192, 192);
        sl.SetCellStyle("A1", "AG" + rowCount, borderAllCell);



        SLStyle borderBottomBlack = sl.CreateStyle();
        borderBottomBlack.Border.BottomBorder.BorderStyle = BorderStyleValues.Thin;
        borderBottomBlack.Border.LeftBorder.Color = System.Drawing.Color.Black;
        sl.SetCellStyle("A1", "AG1", borderBottomBlack);

        borderBottomBlack.Border.BottomBorder.BorderStyle = BorderStyleValues.Medium;
        sl.SetCellStyle("A2", "AG2", borderBottomBlack);


        SLStyle borderRightBlack = sl.CreateStyle();
        borderRightBlack.Border.RightBorder.BorderStyle = BorderStyleValues.Medium;
        borderRightBlack.Border.LeftBorder.Color = System.Drawing.Color.Black;
        sl.SetCellStyle("D1", "D" + rowCount, borderRightBlack);
        sl.SetCellStyle("G1", "G" + rowCount, borderRightBlack);
        sl.SetCellStyle("L1", "L" + rowCount, borderRightBlack);
        sl.SetCellStyle("M1", "M" + rowCount, borderRightBlack);
        sl.SetCellStyle("Q1", "Q" + rowCount, borderRightBlack);
        sl.SetCellStyle("R1", "R" + rowCount, borderRightBlack);
        sl.SetCellStyle("R1", "R" + rowCount, borderRightBlack);
        sl.SetCellStyle("U1", "U" + rowCount, borderRightBlack);
        sl.SetCellStyle("V1", "V" + rowCount, borderRightBlack);
        sl.SetCellStyle("W1", "W" + rowCount, borderRightBlack);
        sl.SetCellStyle("X1", "X" + rowCount, borderRightBlack);
        sl.SetCellStyle("Z1", "Z" + rowCount, borderRightBlack);
        sl.SetCellStyle("AB1", "AB" + rowCount, borderRightBlack);
        sl.SetCellStyle("AC1", "AC" + rowCount, borderRightBlack);

        ///////////////////////////
        // Freeze the top 2 rows //
        ///////////////////////////
        sl.FreezePanes(2, 0);
    }
    private int BuildIAData(ref SLDocument sl)
    {
        //////////////////////////////////////////////////////////////////
        // Lind Of Messy But Also A Little Cool                         //
        // Linq Returning an Anonymous Object Array                     //
        // So Using An Expando Object To Break It Out Into A Dictionary //
        //////////////////////////////////////////////////////////////////
        dynamic incidentAccidentRcdDict = new ExpandoObject();
        var dict = (IDictionary<string, object>)incidentAccidentRcdDict;

        ////////////////////
        // Start at Row 3 //
        ////////////////////
        int row = 3;

        foreach (var incidentAccidentRcd in SqlServer_Impl.GetIncidentAccident())
        {
            foreach (PropertyInfo propertyInfo in incidentAccidentRcd.GetType().GetProperties(BindingFlags.Instance | BindingFlags.Public))
                dict[propertyInfo.Name] = propertyInfo.GetValue(incidentAccidentRcd, null);

            //////////////////////////
            // Incident Disposition //
            //////////////////////////
            sl.SetCellValueNumeric(row, 1, (incidentAccidentRcdDict.iaList.UID).ToString() );
            sl.SetCellValue(row, 2, (string)incidentAccidentRcdDict.iaList.Claim_ID );
            if ( incidentAccidentRcdDict.iaList.Inc_Occur_Date != null )
                sl.SetCellValue(row, 3, ((DateTime)incidentAccidentRcdDict.iaList.Inc_Occur_Date).ToShortDateString() );
            sl.SetCellValue(row, 4, (string)incidentAccidentRcdDict.iaList.Disposition);

            /////////////////////////////
            // Incident Classification //
            /////////////////////////////
            if (incidentAccidentRcdDict.iaList.Inc_Type != null)
                sl.SetCellValue(row, 5, (string)incidentAccidentRcdDict.iaList.Inc_Type);

            if (incidentAccidentRcdDict.iaList.Inc_Type_Sub != null)
                sl.SetCellValue(row, 6, (string)incidentAccidentRcdDict.iaList.Inc_Type_Sub);

            if (incidentAccidentRcdDict.iaList.Inc_Loc != null)
                sl.SetCellValue(row, 7, (string)incidentAccidentRcdDict.iaList.Inc_Loc);

            if (incidentAccidentRcdDict.iaList.Inc_Desc != null)
                sl.SetCellValue(row, 23, (string)incidentAccidentRcdDict.iaList.Inc_Desc);

            if (incidentAccidentRcdDict.iaList.Inc_Unsafe_Act_or_Condition != null)
                sl.SetCellValue(row, 24, (string)incidentAccidentRcdDict.iaList.Inc_Unsafe_Act_or_Condition);

            //////////
            // OSHA //
            //////////
            if (incidentAccidentRcdDict.iaList.Osha_Record_Med != null )
                sl.SetCellValue(row, 8, ( (bool)incidentAccidentRcdDict.iaList.Osha_Record_Med) ? "Yes" : "No");

            if (incidentAccidentRcdDict.iaList.Osha_Restrict_Duty != null)
                sl.SetCellValue(row, 9, ((incidentAccidentRcdDict.iaList.Osha_Restrict_Duty) ? "Yes" : "No"));

            if (incidentAccidentRcdDict.iaList.Osha_Restrict_Days != null)
                sl.SetCellValueNumeric(row, 10, incidentAccidentRcdDict.iaList.Osha_Restrict_Days.ToString());

            if (incidentAccidentRcdDict.iaList.Osha_Lost_Time != null)
                sl.SetCellValue(row, 11, ((incidentAccidentRcdDict.iaList.Osha_Lost_Time) ? "Yes" : "No"));

            if (incidentAccidentRcdDict.iaList.Osha_Lost_Days != null)
                sl.SetCellValueNumeric(row, 12, incidentAccidentRcdDict.iaList.Osha_Lost_Days.ToString());

            ///////////////
            // Drug Test //
            ///////////////
            if (incidentAccidentRcdDict.iaList.Emp_Drug_Alchol_Test != null)
                sl.SetCellValue(row, 13, ((incidentAccidentRcdDict.iaList.Emp_Drug_Alchol_Test) ? "Yes" : "No"));


            //////////////
            // Employee //
            //////////////
            if (incidentAccidentRcdDict.EmpNo != null)
            {
                sl.SetCellValue(row, 14, incidentAccidentRcdDict.EmpDept);
                sl.SetCellValue(row, 15, incidentAccidentRcdDict.EmpNo);
                sl.SetCellValue(row, 16, incidentAccidentRcdDict.EmpLast);
                sl.SetCellValue(row, 17, incidentAccidentRcdDict.EmpFirst);
            }

            ////////////////////
            // Unit / Vehicle //
            ////////////////////
            if (incidentAccidentRcdDict.iaList.Emp_Veh_Involved != null)
                sl.SetCellValue(row, 18, (string)incidentAccidentRcdDict.iaList.Emp_Veh_Involved);

            //////////
            // Supr //
            //////////
            if (incidentAccidentRcdDict.SuprNo != null)
            {
                sl.SetCellValue(row, 19, incidentAccidentRcdDict.SuprNo);
                sl.SetCellValue(row, 20, incidentAccidentRcdDict.SuprLast);
                sl.SetCellValue(row, 21, incidentAccidentRcdDict.SuprFirst);
            }

            ////////////
            // Job No //
            ////////////
            if (incidentAccidentRcdDict.iaList.Emp_Job_No != null)
                sl.SetCellValue(row, 22, (string)incidentAccidentRcdDict.iaList.Emp_Job_No);

            ////////////////
            // Discipline //
            ////////////////
            if (incidentAccidentRcdDict.iaList.Follow_Discipline_Issued_Flag != null)
                sl.SetCellValue(row, 25, ((incidentAccidentRcdDict.iaList.Follow_Discipline_Issued_Flag) ? "Yes" : "No"));

            if (incidentAccidentRcdDict.iaList.Follow_Discipline != null)
                sl.SetCellValue(row, 26, (string)incidentAccidentRcdDict.iaList.Follow_Discipline);

            /////////////////
            // Reoccurance //
            /////////////////
            if (incidentAccidentRcdDict.iaList.Follow_Prevent_Reoccur != null)
                sl.SetCellValue(row, 27, (string)incidentAccidentRcdDict.iaList.Follow_Prevent_Reoccur);

            if (incidentAccidentRcdDict.iaList.Follow_Responsible != null)
                sl.SetCellValue(row, 28, (string)incidentAccidentRcdDict.iaList.Follow_Responsible);

            //////////////////////
            // CLosing Comments //
            //////////////////////
            if (incidentAccidentRcdDict.iaList.Follow_Comments != null)
                sl.SetCellValue(row, 29, (string)incidentAccidentRcdDict.iaList.Follow_Comments);

            //////////
            // Cost //
            //////////
            if (incidentAccidentRcdDict.iaList.Cost_inHouse != null)
                sl.SetCellValueNumeric(row, 30, incidentAccidentRcdDict.iaList.Cost_inHouse.ToString());

            if (incidentAccidentRcdDict.iaList.Cost_Incurred != null)
                sl.SetCellValueNumeric(row, 31, incidentAccidentRcdDict.iaList.Cost_Incurred.ToString());

            if (incidentAccidentRcdDict.iaList.Cost_Reserve != null)
                sl.SetCellValueNumeric(row, 32, incidentAccidentRcdDict.iaList.Cost_Reserve.ToString());

            string xxx = string.Format("=SUM({0})", SLConvert.ToCellRange(row, 30, row, 32));
            sl.SetCellValue(row, 33, xxx);
            
            dict.Clear();
            row++;
        }

        SLStyle styleDataCenter = sl.CreateStyle();
        styleDataCenter.Font.FontName = "Arial";
        styleDataCenter.Font.FontSize = 11;
        styleDataCenter.Font.FontColor = System.Drawing.Color.Black;
        styleDataCenter.Alignment.Horizontal = HorizontalAlignmentValues.Center;
        styleDataCenter.Alignment.Vertical = VerticalAlignmentValues.Center;
        styleDataCenter.SetWrapText(true);
        sl.SetCellStyle("A3", "AG" + row, styleDataCenter);

        SLStyle styleDataLeft = sl.CreateStyle();
        styleDataLeft.Alignment.Horizontal = HorizontalAlignmentValues.Left;
        styleDataLeft.SetWrapText(true);
        sl.SetCellStyle("W3", "W" + row, styleDataLeft);
        sl.SetCellStyle("X3", "X" + row, styleDataLeft);
        sl.SetCellStyle("Z3", "Z" + row, styleDataLeft);
        sl.SetCellStyle("AC3", "AC" + row, styleDataLeft);

        return row - 3;
    }

    private void BuildSumHeader(ref SLDocument sl, int rowCount)
    {
        rowCount += 2;

        /////////////////////////
        // Setup Header Styles //
        /////////////////////////
        SLStyle styleHeaderNormal = sl.CreateStyle();
        styleHeaderNormal.SetWrapText(true);
        styleHeaderNormal.Font.FontName = "Arial";
        styleHeaderNormal.Font.FontSize = 10;
        styleHeaderNormal.Font.FontColor = System.Drawing.Color.Blue;
        styleHeaderNormal.Alignment.Horizontal = HorizontalAlignmentValues.Center;
        styleHeaderNormal.Alignment.Vertical = VerticalAlignmentValues.Bottom;
        sl.SetCellStyle("A1", "Y2", styleHeaderNormal);

        SLStyle styleHeaderBold = styleHeaderNormal;
        styleHeaderBold.Font.Bold = true;
        sl.SetCellStyle("F1", "P2", styleHeaderNormal);

        //////////////////////////////
        // Setup Header Row Heights //
        //////////////////////////////
        sl.SetRowHeight(1, 20);
        sl.SetRowHeight(2, 57);

        ////////////////////////
        // Set Columns Widths //
        ////////////////////////
        sl.SetWorksheetDefaultColumnWidth(13);
        sl.SetColumnWidth("A", 13);
        sl.SetColumnWidth("B", 17);
        sl.SetColumnWidth("C", 13);
        sl.SetColumnWidth("D", 9.43);
        sl.SetColumnWidth("E", 9.43);


        ////////////////////////////////////
        // Merge Some Cells Horiz or Vert //
        ////////////////////////////////////
        sl.MergeWorksheetCells("A1", "A2");
        sl.MergeWorksheetCells("B1", "B2");
        sl.MergeWorksheetCells("C1", "C2");
        sl.MergeWorksheetCells("D1", "D2");
        sl.MergeWorksheetCells("E1", "E2");
        sl.MergeWorksheetCells("Q1", "Q2");
        sl.MergeWorksheetCells("R1", "R2");       
        sl.MergeWorksheetCells("Y1", "Y2");

        sl.MergeWorksheetCells("F1", "P1");
        sl.MergeWorksheetCells("S1", "U1");
        sl.MergeWorksheetCells("V1", "X1");

        SLStyle styleColumnGroup1 = sl.CreateStyle();
        styleColumnGroup1.Fill.SetPatternType(PatternValues.Solid);
        styleColumnGroup1.Fill.SetPatternForegroundColor(System.Drawing.Color.Yellow);
        sl.SetCellStyle("F1", "P2", styleColumnGroup1);


        ////////////////////////////
        // Add Header Text Values //
        ////////////////////////////
        sl.SetCellValue("A1", "Department Numbers");
        sl.SetCellValue("B1", "Department Name");
        sl.SetCellValue("C1", "NAICS Cdoe");
        sl.SetCellValue("D1", "Total Hours Worked");
        sl.SetCellValue("E1", "First Aid Cases");
        sl.SetCellValue("F1", "OSHA REQUIRED INFORMATION");
        sl.SetCellValue("Q1", "Vehicle Incidents");
        sl.SetCellValue("R1", "Vehicle Incident Rate");
        sl.SetCellValue("S1", "Injury Cost");
        sl.SetCellValue("V1", "Vehicle Cost");
        sl.SetCellValue("Y1", "Cost / Man Hour");

        sl.SetCellValue("F2", "Other Recordable Incidents");
        sl.SetCellValue("G2", "Total Recordable Incident Rate (TRIR)");
        sl.SetCellValue("H2", "BLS 2011 National Average");
        sl.SetCellValue("I2", "Job Transfer / Restricted Duty Incidents");
        sl.SetCellValue("J2", "Job Transfer / Restricted Duty Rate (RIR)");
        sl.SetCellValue("K2", "BLS 2011 National Average");
        sl.SetCellValue("L2", "Days Away from Work Incidents");
        sl.SetCellValue("M2", "Days Away from Work Incident Rate (LTRIR)");
        sl.SetCellValue("N2", "BLS 2011 National Average");
        sl.SetCellValue("O2", "Days Away, Restricted, Transferred (DART) Rate");
        sl.SetCellValue("P2", "BLS 2011 National Average");
        sl.SetCellValue("T2", "In-House");
        sl.SetCellValue("S2", "Incurred");
        sl.SetCellValue("U2", "Reserved");
        sl.SetCellValue("T2", "In-House");
        sl.SetCellValue("S2", "Incurred");
        sl.SetCellValue("U2", "Reserved");

        //////////////////////////////
        // Create Soft Cell Borders //
        //////////////////////////////
        SLStyle borderAllCell = sl.CreateStyle();
        borderAllCell.Border.RightBorder.BorderStyle = BorderStyleValues.Thin;
        borderAllCell.Border.BottomBorder.BorderStyle = BorderStyleValues.Thin;
        borderAllCell.Border.RightBorder.Color = System.Drawing.Color.FromArgb(100, 192, 192, 192);
        borderAllCell.Border.BottomBorder.Color = System.Drawing.Color.FromArgb(100, 192, 192, 192);
        sl.SetCellStyle("A1", "W" + rowCount, borderAllCell);

        /////////////////////////////
        // Create Hard Row Borders //
        /////////////////////////////
        SLStyle borderBottomBlack = sl.CreateStyle();
        borderBottomBlack.Border.BottomBorder.BorderStyle = BorderStyleValues.Thin;
        borderBottomBlack.Border.LeftBorder.Color = System.Drawing.Color.Black;
        sl.SetCellStyle("A1", "Y1", borderBottomBlack);

        borderBottomBlack.Border.BottomBorder.BorderStyle = BorderStyleValues.Medium;
        sl.SetCellStyle("A2", "Y2", borderBottomBlack);


        ////////////////////////////////
        // Create Hard Column Borders //
        ////////////////////////////////
        SLStyle borderRightBlack = sl.CreateStyle();
        borderRightBlack.Border.RightBorder.BorderStyle = BorderStyleValues.Medium;
        borderRightBlack.Border.LeftBorder.Color = System.Drawing.Color.Black;
        sl.SetCellStyle("A1", "E" + rowCount, borderRightBlack);
        sl.SetCellStyle("H1", "H" + rowCount, borderRightBlack);
        sl.SetCellStyle("K1", "K" + rowCount, borderRightBlack);
        sl.SetCellStyle("N1", "N" + rowCount, borderRightBlack);
        sl.SetCellStyle("P1", "P" + rowCount, borderRightBlack);
        sl.SetCellStyle("R1", "R" + rowCount, borderRightBlack);
        sl.SetCellStyle("U1", "U" + rowCount, borderRightBlack);
        sl.SetCellStyle("W1", "W" + rowCount, borderRightBlack);
        sl.SetCellStyle("Y1", "Y" + rowCount, borderRightBlack);



        ///////////////////////////
        // Freeze the top 2 rows //
        ///////////////////////////
        sl.FreezePanes(2, 0);
    }
}