<%@ Page Title="" Language="C#" MasterPageFile="~/SiteMaster2.master" AutoEventWireup="true" CodeFile="BugReportList.aspx.cs" Inherits="Forms_BugReportList" %>
<%@ Register TagPrefix="asp" Namespace="AjaxControlToolkit" Assembly="AjaxControlToolkit, Version=4.1.60623.0, Culture=neutral, PublicKeyToken=28f01b0e84b6d53e" %>

<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" Runat="Server">
    <title>Bug Report Admin / List</title>
    <style>
        .VerticleAlignTop {
            vertical-align: top;
        }
    </style>
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" Runat="Server">
    <asp:ToolkitScriptManager ID="ToolkitScriptManager1" runat="Server" />

<!----------------->
<!-- Form Header -->
<!----------------->           
    <div class="ui-widget-header ui-corner-all" >
        <div  style="text-align: center; font-size: 2em;">Safety Pays Administration</div>
    </div>
        

    <div class="ui-widget-content ui-corner-all">                 
        <asp:Panel ID="pnlGridView" runat="server">
            <div style="height: 15px;"></div>    

            <table style="margin-left: auto; margin-right: auto;">
                    <tr>
                        <td>
                            <SIU:SelfSortingGrid ID="gvBugReportAdmin" runat="server"
                    
                                AutoGenerateColumns="False" 
                                AutoGenerateSelectButton="False" 
                                AutoGenerateEditButton="False"
                                AutoGenerateDeleteButton="False"
                     
                                AllowSorting="True"
                                AllowPaging="True" 
                                EmptyDataText="No Open Reports or Data Access Problem." 
                                ShowFooter="False"
                    
                                PageSize="15" 
                                CellPadding="2" 
                                CellSpacing="2" 

                                BorderStyle="None"
                                
                                DataSourceID="OdsStatus"
                                DataKeyNames="IncidentNo"
                                     
                                OnRowEditing="gvBugReportAdmin_RowEditing" 
                                OnSelectedIndexChanged="gvBugReportAdmin_SelectedIndexChanged" 
                                OnRowDataBound="gvBugReportAdmin_RowDataBound"
                                    
                                OnPageIndexChanging="gvBugReportAdmin_PageIndexChanging" 
                                OnSorting="gvBugReportAdmin_Sorting" 
                                >
                                    
                                <RowStyle CssClass="TableRowCss"></RowStyle>

                                <AlternatingRowStyle BackColor="#333333" />
                                <Columns>
                                        
                                    <%-- Edit Command --%>
                                    <asp:TemplateField HeaderStyle-BorderStyle="None" 
                                        HeaderText="Status">
                                        <HeaderStyle BorderStyle="None" />
                                        <ItemStyle CssClass="TableRowCss VerticleAlignTop" />
                                        <ItemTemplate>
                                            <asp:Label ID="lblStatus" runat="server"></asp:Label>

                                            <asp:LinkButton ID="LinkAccept" Runat="server" CausesValidation="False" CommandName="edit" OnClick="lblBtnAccept_Click">
                                                <span style="font-weight: bold;">A</span>
                                            </asp:LinkButton>
                                                                                        
                                            <asp:LinkButton ID="LinkWork" Runat="server" CausesValidation="False" CommandName="edit" OnClick="lblBtnWork_Click">
                                                <span style="font-weight: bold;">W</span>
                                            </asp:LinkButton>
                                            
                                            <asp:LinkButton ID="LinkTest" Runat="server" CausesValidation="False" CommandName="edit" OnClick="lblBtnTest_Click">
                                                <span style="font-weight: bold;">T</span>
                                            </asp:LinkButton>
                                            
                                            <asp:LinkButton ID="LinkReject" Runat="server" CausesValidation="False" CommandName="edit" OnClick="lblBtnReject_Click">
                                                <span style="font-weight: bold;">R</span>
                                            </asp:LinkButton>
                                            
                                        </ItemTemplate>
                                    </asp:TemplateField>

                                    <%-- Report ID --%>
                                    <asp:TemplateField HeaderStyle-BorderStyle="None" HeaderText="ID" 
                                        SortExpression="TaskNo">
                                        <HeaderStyle BorderStyle="None" />
                                        <ItemStyle CssClass="TableRowCss2 VerticleAlignTop" />
                                        <ItemTemplate>
                                            <asp:Label ID="lblId" runat="server" Text='<%# Bind("IncidentNo") %>'></asp:Label>
                                        </ItemTemplate>
                                    </asp:TemplateField>

                                    <%-- Employee Email --%>
                                    <asp:TemplateField HeaderStyle-BorderStyle="None" HeaderText="Employee" 
                                        SortExpression="EmpEmail">
                                        <HeaderStyle BorderStyle="None" />
                                        <ItemStyle CssClass="TableRowCss2 VerticleAlignTop" HorizontalAlign="Center" />
                                        <ItemTemplate>
                                            <asp:Label ID="lblEmail" runat="server" Text='<%# Bind("EmpEmail") %>'></asp:Label>
                                        </ItemTemplate>
                                    </asp:TemplateField>

                                    <%-- Report Opened Date --%>
                                    <asp:TemplateField HeaderStyle-BorderStyle="None" HeaderText="Dates (OAWTRC)" 
                                        SortExpression="IncOpenTimestamp">
                                        <HeaderStyle BorderStyle="None" />
                                        <ItemStyle CssClass="TableRowCss VerticleAlignTop" />
                                        <ItemTemplate>
                                            <asp:Label ID="lblOpenDate" runat="server"></asp:Label>
                                        </ItemTemplate>
                                    </asp:TemplateField>

                                    <%-- Description --%>
                                    <asp:TemplateField HeaderStyle-BorderStyle="None" HeaderText="Comments" >
                                        <HeaderStyle BorderStyle="None" />
                                        <ItemStyle CssClass="TableRowCss VerticleAlignTop" />
                                        <ItemTemplate>
                                            <asp:Label ID="lblDesc" runat="server" Width="300" Text='<%# Bind("Description") %>'></asp:Label>
                                        </ItemTemplate>
                                    </asp:TemplateField>

                                    <%-- Steps --%>
                                    <asp:TemplateField HeaderStyle-BorderStyle="None" HeaderText="Steps" >
                                        <HeaderStyle BorderStyle="None" />
                                        <ItemStyle CssClass="TableRowCss VerticleAlignTop" />
                                        <ItemTemplate>
                                            <asp:Label ID="lblSteps" runat="server" Width="300" Text='<%# Bind("StepsToCreate")%>' ></asp:Label>
                                        </ItemTemplate>
                                    </asp:TemplateField>
                                    
                                    <%-- Testing Reject --%>
                                    <asp:TemplateField HeaderStyle-BorderStyle="None" HeaderText="Test Reject Notes" >
                                        <HeaderStyle BorderStyle="None" />
                                        <ItemStyle CssClass="TableRowCss VerticleAlignTop" />
                                        <ItemTemplate>
                                            <asp:Label ID="lblReject" runat="server" Width="300" Text='<%# Bind("TestRejectionNotes") %>'></asp:Label>
                                        </ItemTemplate>
                                    </asp:TemplateField>

                                </Columns>

                                <PagerStyle HorizontalAlign="Left"/>
                            </SIU:SelfSortingGrid>
                        </td>
                    </tr>
            </table>
        </asp:Panel> 
    </div>

    <asp:ObjectDataSource ID="OdsStatus"    runat="server" TypeName="SqlServer_Impl" SelectMethod="GetBugReportList"></asp:ObjectDataSource>
</asp:Content>

