<%@ Page Title="" Language="C#" MasterPageFile="~/SiteMaster2.master" AutoEventWireup="true" CodeFile="QualCodes.aspx.cs" Inherits="Forms_QualCodes" %>
<%@ Register TagPrefix="asp" Namespace="AjaxControlToolkit" Assembly="AjaxControlToolkit, Version=4.1.60623.0, Culture=neutral, PublicKeyToken=28f01b0e84b6d53e" %>


<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" Runat="Server">
    <%-- Development--%>

<%--    
    <script type="text/javascript">
        $(document).ready(function () {

            var refDdInsertCategory = $("#ddInsertCat");
            var refTxtInsertCategory = $("#txtInsertCat");

            refDdInsertCategory.blur(function () {
                if (refTxtInsertCategory.is(":visible")) {
                    var selectedVal = refDdInsertCategory.val();
                    var selectedIndex = refDdInsertCategory.get(0).selectedIndex;
                    var newVal = refTxtInsertCategory.val();

                    if (selectedIndex > 0) {
                        refTxtInsertCategory.val(selectedVal);
                        selectedIndex = 0;
                    }
                }
            });



        })
    </script>
    --%>
    

    <style>
        .NewCatTxtBox 
        {
            width: 390px;
        } 

        html {
            xbackground-color: #45473f;
            background-color: black;
        }
    </style>

</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" Runat="Server">
    
    <asp:ToolkitScriptManager ID="ToolkitScriptManager1" runat="Server" />

    <div style="xbackground-color: #45473f;">
        <div id="FormWrapper" class="ui-widget ui-form" style=" width: 100%; ">
            
    <!----------------->
    <!-- Form Header -->
    <!----------------->           
            <div class="ui-widget-header ui-corner-all" >
                <div  style="text-align: center; font-size: 2em;">Certification Codes</div>
            </div>
        

            <div class="ui-widget-content" style="border: none;">                 
                <asp:Panel ID="pnlGridView" runat="server" Width="100%">
    
 
    <!------------------>
    <!-- Search Panel -->
    <!------------------>
                    <div style="background-color: black; border: 2px solid red; margin-top: -10px;">
            
                        <div>
                            <asp:Button ID="btnSearch" runat="server" OnClick="btnSearch_Click" Text="Search"  CssClass="SearchBtnCSS"/>
                            <span style=" color: white; font-size: 1.4em; padding-left: 15px; padding-right: 5px; float: left;"> Code</span>
                            <asp:TextBox ID="txtSearchCode" runat="server" MaxLength="30"  CssClass="SearchTextBoxCSS"  />
                            <span style="width: 10px;">&nbsp;</span>
                            <asp:DropDownList runat="server" ID="ddSearchCategory" CssClass="SearchTextBoxCSS" Width="360px" DataSourceID="ObjectDataSource1"></asp:DropDownList>
                        </div>
            
                    </div>
        
                    <div style="height: 25px;"></div>
    
    
                    
    <!---------------->
    <!-- List Panel -->
    <!---------------->

                    <table>
                        <tr>
                            <td>
<div style="margin-right: auto; margin-left: auto; width: 100%; background-color: lightgrey; color: black;">                                
                                <SIU:SelfSortingGrid ID="gvQualCodes" runat="server"
                    
                                    AutoGenerateColumns="False" 
                                    AutoGenerateSelectButton="False" 
                                    AutoGenerateEditButton="False"
                                    AutoGenerateDeleteButton="False"
                     
                                    AllowSorting="True"
                                    AllowPaging="True" 
                                    EmptyDataText="Data Access Problem." 
                                    ShowFooter="False"
                    
                                    PageSize="15" 
                                    CellPadding="2" 
                                    CellSpacing="2" 
                    
                                    OnPageIndexChanging="gvQualCodes_PageIndexChanging" 
                                    OnSorting="gvQualCodes_Sorting" 
                                    OnRowDeleting="gvQualCodes_RowDeleting" 
                                    OnRowDataBound="gvQualCodes_RowDataBound" 
                                    OnSelectedIndexChanged="gvQualCodes_SelectedIndexChanged" 
                        
                                    OnRowCancelingEdit="gvQualCodes_RowCancelingEdit" 
                                    OnDataBound="dvQualCode_DataBound"
                        
                                    OnRowEditing="gvQualCodes_RowEditing" 
                                    OnRowUpdating="gvQualCodes_RowUpdating"
                         
                                    OnRowCommand="gvQualCodes_RowCommand" 
                                    
                                    BorderStyle="None"
                                    
                                    Width="100%"
                                    >

                                    <Columns>
                                        
                                        <%-- Edit Command --%>
                                        <asp:TemplateField  HeaderText="Edit&nbsp;&nbsp;&nbsp;"  HeaderStyle-BorderStyle="None">
                                            <ItemStyle BorderStyle="None" />
                                            <ItemTemplate>

                                                <asp:LinkButton Runat="server" CausesValidation="False" CommandName="Edit">
                                                    <img src="/Images/edit.png" alt="edit" style="border: 0; height: 24px; width: 24px; margin-right: 15px; margin-left: 5px;"/>
                                                </asp:LinkButton>
                                                
                                            </ItemTemplate> 
                                        </asp:TemplateField>  
                                                       
                                        <%-- Qualification Code Value --%>
                                        <asp:TemplateField HeaderText="Qual Code" SortExpression="Code" HeaderStyle-BorderStyle="None" HeaderStyle-ForeColor="Black"  >
                                            <ItemStyle />

                                            <ItemTemplate>
				                                <asp:Label ID="lblCode" runat="server" Text='<%# Bind("Code") %>' ></asp:Label>
				                            </ItemTemplate>

                                        </asp:TemplateField>                        
                            
                                        <%-- Qualification Code Description --%>
                                        <asp:TemplateField HeaderText="Description" SortExpression="Description" HeaderStyle-BorderStyle="None" HeaderStyle-ForeColor="Black" >
                                            <ItemStyle />

                                            <ItemTemplate>
				                                <asp:Label ID="lblDesc" runat="server" Text='<%# Bind("Description") %>' ></asp:Label>
				                            </ItemTemplate>

                                        </asp:TemplateField>             
                            
                            
                                        <%-- Qualification Code Duration --%>
                                        <asp:TemplateField HeaderText="Mo" HeaderStyle-BorderStyle="None" >
                                            <ItemStyle HorizontalAlign="Center" />

                                            <ItemTemplate>
				                                <asp:Label ID="lblDuration" runat="server" Text='<%# Bind("Duration_of_Certification") %>' ></asp:Label>
				                            </ItemTemplate>

                                        </asp:TemplateField> 
                            
                                        <%-- Qualification Code Category --%>
                                        <asp:TemplateField HeaderText="Category" SortExpression="Category" HeaderStyle-BorderStyle="None" HeaderStyle-ForeColor="Black" >
                                            <ItemStyle HorizontalAlign="Center"/>

                                            <ItemTemplate>
				                                <asp:Label ID="lblCategory" runat="server" Text='<%# Bind("Category") %>' ></asp:Label>
				                            </ItemTemplate>

                                        </asp:TemplateField>                              
                                        
                                        
                                        <%-- Number Of Employees With Qualification Code --%>
                                        <asp:TemplateField HeaderText="Emp." HeaderStyle-BorderStyle="None">
                                            <ItemStyle HorizontalAlign="Center"/>

                                            <ItemTemplate>
				                                <asp:Label runat="server" ID="lblCodeEmpCnt"></asp:Label>
				                            </ItemTemplate>

                                        </asp:TemplateField>  
                                        
                                        
                                        
                                        <%-- Delete Command --%>
                                        <asp:TemplateField  HeaderText="&nbsp;&nbsp;&nbsp;Del" HeaderStyle-BorderStyle="None">
                                            <ItemStyle BorderStyle="None"  />
                                            <ItemTemplate>
                                                
                                                <asp:LinkButton ID="LinkButton1" Runat="server" CausesValidation="False" CommandName="Delete" OnClientClick="return confirm('Are you sure you want to delete this Code?');">
                                                    <img src="/Images/Delete.png"  alt="del" style="border: 0; height: 24px; width: 24px; margin-left: 20px;"/>
                                                </asp:LinkButton>

                                            </ItemTemplate> 
                                        </asp:TemplateField> 

                                    </Columns>

                                    <PagerStyle HorizontalAlign="Left"/>
                                </SIU:SelfSortingGrid>
</div>
                            </td>
                        </tr>
            
                        <tr>
                            <td>
                                <asp:Button ID="lblBtnShowDetail" runat="server" OnClick="lblBtnAddDetail_Click" Text="Add New Code"  CssClass="SearchBtnCSS"/>
                            </td>
                        </tr>


                    </table>

                </asp:Panel>
    
    

            <!------------------------->
            <!-- Edit / Insert Panel -->
            <!------------------------->
            <div style="width: 350px; margin-left: auto;  margin-right: auto;"> 
                <asp:Panel ID="pnlDetailsView" runat="server" Width="100%">

                    <div style="height: 60px; margin-top: -20px;">
                        <div id="EditFormHeader" style="text-align: center; font-size: 1.8em; ">Update Code</div>
                    </div> 
                    
                           
                    <table>
                        <tr>
                            <td>
                                <asp:DetailsView ID="dvQualCode" runat="server" 
                                    AllowPaging="False" 
                                    GridLines="None"
                      
                                    AutoGenerateDeleteButton="False" 
                                    AutoGenerateEditButton="True" 
                                    AutoGenerateInsertButton="True"  
                                    AutoGenerateRows="False" 

                                    DefaultMode="Edit"

                                    BorderStyle="Solid"
                                    BorderWidth="1px"  
                                    CellPadding="3" 
                                    CaptionAlign="Left" 
                    
                                    EmptyDataText="No Code found." 
                    
                                    OnItemDeleting="dvQualCode_ItemDeleting" 
                                    OnItemInserting="dvQualCode_ItemInserting"
                                    OnItemUpdating="dvQualCode_ItemUpdating"  
                                    ondatabound="dvQualCode_DataBound" onmodechanging="dvQualCode_ModeChanging"                  
                                    >
                                    <Fields>


                                            <%-- Qualification Code Value --%>
                                            <asp:TemplateField HeaderText="Qual Code" SortExpression="Code">
                                                <ItemTemplate>
				                                    <asp:Label ID="dv_lblCode" runat="server" Text='<%# Bind("Code") %>'></asp:Label>
				                                </ItemTemplate>
                                
                                                <InsertItemTemplate>    
				                                    <asp:TextBox ID="txtInsertCode" runat="server" Text='<%# Bind("Code") %>' MaxLength="25" />
                                                    
                                                    <asp:RequiredFieldValidator
                                                        ID="rvInsertCode" runat="server" ErrorMessage="Code Can Not Be Blank" ControlToValidate="txtInsertCode">&nbsp;
                                                    </asp:RequiredFieldValidator>

                                                    <ajaxToolkit:ValidatorCalloutExtender 
                                                        runat="Server" ID="ExtRvInsertCode" TargetControlID="rvInsertCode" Width="350px"
                                                        HighlightCssClass="highlight" CssClass="CustomValidatorCalloutStyle" PopupPosition="Right"
                                                        WarningIconImageUrl="/Images/warning.gif" CloseImageUrl="/Images//close.png" />

                                                </InsertItemTemplate>
                                            </asp:TemplateField> 
                            
                            

                                            <%-- Qualification Code Description --%>
                                            <asp:TemplateField HeaderText="Description" SortExpression="Description">
                                                <ItemTemplate>
				                                    <asp:Label ID="lblDesc" runat="server" Text='<%# Bind("Description") %>' ></asp:Label>
				                                </ItemTemplate>

                                                <EditItemTemplate>
				                                    <asp:TextBox ID="txtEditDesc" runat="server" Text='<%# Bind("Description") %>' MaxLength="80"  />
                                                    
                                                    <asp:RequiredFieldValidator
                                                        ID="rvEditDesc" runat="server" ErrorMessage="Description Can Not Be Blank" ControlToValidate="txtEditDesc">&nbsp;
                                                    </asp:RequiredFieldValidator>

                                                    <ajaxToolkit:ValidatorCalloutExtender 
                                                        runat="Server" ID="ExtRvEditDesc" TargetControlID="rvEditDesc" Width="350px"
                                                        HighlightCssClass="highlight" CssClass="CustomValidatorCalloutStyle" PopupPosition="Right"
                                                        WarningIconImageUrl="/Images/warning.gif" CloseImageUrl="/Images//close.png" />
                                                </EditItemTemplate>                            

                                                <InsertItemTemplate>    
				                                    <asp:TextBox ID="txtInsertDesc" runat="server" Text='<%# Bind("Description") %>' MaxLength="80"  />

                                                    <asp:RequiredFieldValidator
                                                        ID="rvInsertDesc" runat="server" ErrorMessage="Description Can Not Be Blank" ControlToValidate="txtInsertDesc">&nbsp;
                                                    </asp:RequiredFieldValidator>

                                                    <ajaxToolkit:ValidatorCalloutExtender 
                                                        runat="Server" ID="ExtRvInsertDesc" TargetControlID="rvInsertDesc" Width="350px"
                                                        HighlightCssClass="highlight" CssClass="CustomValidatorCalloutStyle" PopupPosition="Right"
                                                        WarningIconImageUrl="/Images/warning.gif" CloseImageUrl="/Images//close.png" />
                                                </InsertItemTemplate>
                                            </asp:TemplateField>  
                            
                            
                            

                                            <%-- Qualification Code Duration --%>
                                            <asp:TemplateField HeaderText="Duration" >
                                                <ItemTemplate>
				                                    <asp:Label ID="lblDuration" runat="server" Text='<%# Bind("Duration_of_Certification") %>' ></asp:Label>
				                                </ItemTemplate>

                                                <EditItemTemplate>
				                                    <asp:TextBox ID="txtEditDuration" runat="server" Text='<%# Bind("Duration_of_Certification") %>' MaxLength="80"  />
                                                    
                                                    <asp:RangeValidator ID="rvEditDur" runat="server" ErrorMessage="Duration Must Be Between 1 and 9999" 
                                                                        Display="Dynamic" ControlToValidate="txtEditDuration" Type="Integer" MinimumValue="1" MaximumValue="9999">&nbsp;
                                                    </asp:RangeValidator>
                                                    
                                                    <asp:RequiredFieldValidator
                                                        ID="rvEditDurReq" runat="server" ErrorMessage="Duration Can Not Be Blank" ControlToValidate="txtEditDuration">&nbsp;
                                                    </asp:RequiredFieldValidator>

                                                    <ajaxToolkit:ValidatorCalloutExtender 
                                                        runat="Server" ID="ExtRvEditDur" TargetControlID="rvEditDur" Width="350px"
                                                        HighlightCssClass="highlight" CssClass="CustomValidatorCalloutStyle" PopupPosition="Right"
                                                        WarningIconImageUrl="/Images/warning.gif" CloseImageUrl="/Images//close.png" />
                                                        
                                                    <ajaxToolkit:ValidatorCalloutExtender 
                                                        runat="Server" ID="ExtRvEditDescReq" TargetControlID="rvEditDurReq" Width="350px"
                                                        HighlightCssClass="highlight" CssClass="CustomValidatorCalloutStyle" PopupPosition="Right"
                                                        WarningIconImageUrl="/Images/warning.gif" CloseImageUrl="/Images//close.png" />
                                                </EditItemTemplate>                            

                                                <InsertItemTemplate>    
				                                    <asp:TextBox ID="txtInsertDuration" runat="server" Text='<%# Bind("Duration_of_Certification") %>' MaxLength="80"  />

                                                    <asp:RangeValidator ID="rvInsertDur" runat="server" ErrorMessage="Duration Must Be Between 1 and 9999" 
                                                                        Display="Dynamic" ControlToValidate="txtInsertDuration" Type="Integer" MinimumValue="1" MaximumValue="9999">&nbsp;
                                                    </asp:RangeValidator>
                                                    
                                                    <asp:RequiredFieldValidator
                                                        ID="rvInsertDurReq" runat="server" ErrorMessage="Duration Can Not Be Blank" ControlToValidate="txtInsertDuration">&nbsp;
                                                    </asp:RequiredFieldValidator>

                                                    <ajaxToolkit:ValidatorCalloutExtender 
                                                        runat="Server" ID="ExtRvInsertDur" TargetControlID="rvInsertDur" Width="350px"
                                                        HighlightCssClass="highlight" CssClass="CustomValidatorCalloutStyle" PopupPosition="Right"
                                                        WarningIconImageUrl="/Images/warning.gif" CloseImageUrl="/Images//close.png" />
                                                        
                                                    <ajaxToolkit:ValidatorCalloutExtender 
                                                        runat="Server" ID="ExtRvInsertDescReq" TargetControlID="rvInsertDurReq" Width="350px"
                                                        HighlightCssClass="highlight" CssClass="CustomValidatorCalloutStyle" PopupPosition="Right"
                                                        WarningIconImageUrl="/Images/warning.gif" CloseImageUrl="/Images//close.png" />

                                                </InsertItemTemplate>
                                            </asp:TemplateField>  
                            
                            
                            
                                            <%-- Qualification Code Category --%>
                                            <asp:TemplateField HeaderText="Category" SortExpression="Category">
                                                <ItemTemplate>
				                                    <asp:Label ID="lblCat" runat="server" Text='<%# Bind("Category") %>' ></asp:Label>
				                                </ItemTemplate>

                                                <EditItemTemplate>
				                                    <asp:TextBox ID="txtEditCat" runat="server" Text='<%# Bind("Category") %>' MaxLength="80" />
                                                    
                                                        <asp:AutoCompleteExtender   
                                                           ID="AutoCompleteExtender2"   
                                                           TargetControlID="txtEditCat"   
                                                           runat="server" 
                                                           ServicePath="~/Forms/QualCodes.aspx" 
                                                           ServiceMethod="GetCompletionList" 
                                                           MinimumPrefixLength="1" 
                                                           Enabled="True" 
                                                           UseContextKey="True" 
                                                           CompletionInterval="500" /> 

                                                    <asp:RequiredFieldValidator
                                                        ID="rvEditCatReq" runat="server" ErrorMessage="Category Can Not Be Blank" ControlToValidate="txtEditCat">&nbsp;
                                                    </asp:RequiredFieldValidator>
                                                    
                                                    <ajaxToolkit:ValidatorCalloutExtender 
                                                        runat="Server" ID="ExtRvEditCatReq" TargetControlID="rvEditCatReq" Width="350px"
                                                        HighlightCssClass="highlight" CssClass="CustomValidatorCalloutStyle" PopupPosition="Right"
                                                        WarningIconImageUrl="/Images/warning.gif" CloseImageUrl="/Images//close.png" />
                                                </EditItemTemplate>                            

                                                <InsertItemTemplate>
                                                    <div>
                                                        <asp:TextBox ID="txtInsertCat" runat="server" Text='<%# Bind("Category") %>' MaxLength="80" CssClass="NewCatTxtBox"   />
                                                        <asp:AutoCompleteExtender   
                                                           ID="AutoCompleteExtender1"   
                                                           TargetControlID="txtInsertCat"   
                                                           runat="server" 
                                                           ServicePath="~/Forms/QualCodes.aspx" 
                                                           ServiceMethod="GetCompletionList" 
                                                           MinimumPrefixLength="1" 
                                                           Enabled="True" 
                                                           UseContextKey="True" CompletionInterval="500" />  

                                                    </div>
                                                    
                                                    <asp:RequiredFieldValidator
                                                        ID="rvInsertCatReq" runat="server" ErrorMessage="Category Can Not Be Blank" ControlToValidate="txtInsertCat">&nbsp;
                                                    </asp:RequiredFieldValidator>
                                                    
                                                    <ajaxToolkit:ValidatorCalloutExtender 
                                                        runat="Server" ID="ExtRvInsertCatReq" TargetControlID="rvInsertCatReq" Width="350px"
                                                        HighlightCssClass="highlight" CssClass="CustomValidatorCalloutStyle" PopupPosition="Right"
                                                        WarningIconImageUrl="/Images/warning.gif" CloseImageUrl="/Images//close.png" />
                                                </InsertItemTemplate>
                                            </asp:TemplateField> 
                                            
                                    </Fields>                                                  
                                    </asp:DetailsView>

                            </td>
                        </tr>
                    </table>
               
                </asp:Panel> 
</div>                    
            </div>
        </div>    
    </div>

    <asp:ObjectDataSource ID="ObjectDataSource1" runat="server" TypeName="SqlServer_Impl" SelectMethod="Please_Select_GetBandC_QualCategories"></asp:ObjectDataSource>

</asp:Content>


