<%@ Page Title="" Language="C#" MasterPageFile="~/SiteMaster2.master" AutoEventWireup="true" CodeFile="SafetyQoMAnsAdmin.aspx.cs" Inherits="Forms_SafetyQomAnsAdmin" %>
<%@ Register TagPrefix="asp" Namespace="AjaxControlToolkit" Assembly="AjaxControlToolkit, Version=4.1.60623.0, Culture=neutral, PublicKeyToken=28f01b0e84b6d53e" %>

<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" Runat="Server">
    <title>Admin View For Safety Question Of the Month</title>
    
    <style>
        .CenterCss {
            color: orange;
        }
        
        .ScoreCss {
            margin-top: 5px;
            width: 25px;
            border: 2px solid red;
        }
    </style>
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" Runat="Server">
    <asp:ToolkitScriptManager ID="ToolkitScriptManager1" runat="Server" />
    
<!----------------->
<!-- Form Header -->
<!----------------->           
    <div class="ui-widget-header ui-corner-all" >
        <div  style="text-align: center; font-size: 2em;">Safety Pays Administration</div>
    </div>
    
    <div class="ui-widget-content ui-corner-all">
        <asp:Panel ID="pnlSelectView" runat="server">
           
            <div style="height: 15px;"></div>    

            <SIU:SelfSortingGrid ID="gvSafetyQomAnsAdminSelect" runat="server" CssClass="GridCenterCss"
                    
                AutoGenerateColumns="False" 
                AutoGenerateSelectButton="False" 
                AutoGenerateEditButton="False"
                AutoGenerateDeleteButton="False"
                     
                AllowSorting="False"
                AllowPaging="False" 
                EmptyDataText="Currently All Responses Have Been Scored.  (Or Data Access Problem)" 
                ShowFooter="False"
                            
                DataSourceID="OdsSelect"
                DataKeyNames="Q_Id"
                    
                PageSize="15" 
                CellPadding="2" 
                CellSpacing="2" 

                BorderStyle="None"
                                     
                OnRowEditing="gvSafetyQomAnsAdminSelect_RowEditing" 
                OnSelectedIndexChanged="gvSafetyQomAnsAdminSelect_SelectedIndexChanged" 
                OnRowDataBound="gvSafetyQomAnsAdminSelect_RowDataBound"
                                    
                OnPageIndexChanging="gvSafetyQomAnsAdminSelect_PageIndexChanging" 
                OnSorting="gvSafetyQomAnsAdminSelect_Sorting" 
                >
                                    
                <RowStyle CssClass="TableRowCss"></RowStyle>
                <SelectedRowStyle CssClass="SelectedTableRowCss"></SelectedRowStyle>

                <AlternatingRowStyle BackColor="#333333" />
                <Columns>
                                        
                    <%-- Edit Command --%>
                    <asp:TemplateField HeaderStyle-BorderStyle="None" 
                        HeaderText="Edit&nbsp;&nbsp;&nbsp;">
                        <HeaderStyle BorderStyle="None" />
                        <ItemStyle CssClass="TableRowCss" />
                        <ItemTemplate>
                            <asp:LinkButton ID="LinkButton1" Runat="server" CausesValidation="False" 
                                CommandName="Edit">
                                <img src="/Images/edit.png" alt="edit" style="border: 0; height: 24px; width: 24px; margin-right: 15px; margin-left: 0;"/>
                            </asp:LinkButton>
                        </ItemTemplate>
                    </asp:TemplateField>

                    <%-- Question ID --%>
                    <asp:TemplateField HeaderStyle-BorderStyle="None" HeaderText="ID" 
                        SortExpression="Q_Id">
                        <HeaderStyle BorderStyle="None" />
                        <ItemStyle CssClass="TableRowCss2" />
                        <ItemTemplate>
                            <asp:Label ID="lblId" runat="server" Text='<%# Bind("Q_Id") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>

                    <%-- Start Date --%>
                    <asp:TemplateField HeaderStyle-BorderStyle="None" HeaderText="Start" 
                        SortExpression="StartDate">
                        <HeaderStyle BorderStyle="None" />
                        <ItemStyle CssClass="TableRowCss2" HorizontalAlign="Center" />
                        <ItemTemplate>
                            <asp:Label ID="lblStartDate" runat="server" Text='<%# Bind("StartDate") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>

                    <%-- End Date Date --%>
                    <asp:TemplateField HeaderStyle-BorderStyle="None" HeaderText="End Date" 
                        SortExpression="End Date">
                        <HeaderStyle BorderStyle="None" />
                        <ItemStyle CssClass="TableRowCss" />
                        <ItemTemplate>
                            <asp:Label ID="lblEndDate" runat="server" Text='<%# Bind("EndDate") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>

                    <%-- Report Type --%>
                    <asp:TemplateField HeaderStyle-BorderStyle="None" HeaderText="Question" 
                        SortExpression="IncTypeTxt">
                        <HeaderStyle BorderStyle="None" />
                        <ItemStyle CssClass="TableRowCss" />
                        <ItemTemplate>
                            <asp:Label ID="lblType" runat="server" Text='<%# Bind("Question") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>

                </Columns>

                <PagerStyle HorizontalAlign="Left"/>
            </SIU:SelfSortingGrid>

        </asp:Panel>         
        
        
        <br/>
        
                         
        <asp:Panel ID="pnlDetailsView" runat="server">
            
            <div style="margin-left: auto; margin-right: auto;">
                <SIU:SelfSortingGrid ID="gvSafetyQomAnsAdmin" runat="server" CssClass="GridCenterCss"
                    
                    AutoGenerateColumns="False" 
                    AutoGenerateSelectButton="False" 
                    AutoGenerateEditButton="False"
                    AutoGenerateDeleteButton="False"
                     
                    AllowSorting="True"
                    AllowPaging="True" 
                    
                    DataSourceID="OdsPoints"
                    DataKeyNames="Q_Id, ANs_Id"

                    ShowFooter="False"
                    
                    PageSize="10" 
                    CellPadding="2" 
                    CellSpacing="2" 

                    BorderStyle="None"
                                     
                    OnRowEditing="gvSafetyQomAnsAdmin_RowEditing" 
                    OnSelectedIndexChanged="gvSafetyQomAnsAdmin_SelectedIndexChanged" 
                                    
                    OnPageIndexChanging="gvSafetyQomAnsAdmin_PageIndexChanging" 
                    OnSorting="gvSafetyQomAnsAdmin_Sorting" 
                    OnRowDataBound="gvSafetyQomAnsAdmin_RowDataBound"
                 >
                                    
                    <RowStyle CssClass="TableRowCss"></RowStyle>
                    

                    <AlternatingRowStyle BackColor="#333333" />
                    <Columns>
                        
                        <%--Answer ID--%>
                        <asp:TemplateField HeaderStyle-BorderStyle="None" HeaderText="Ans" >
                            <HeaderStyle BorderStyle="None" />
                            <ItemStyle CssClass="TableRowCss" HorizontalAlign="Center" />
                            <FooterStyle BorderStyle="None"></FooterStyle>

                            <ItemTemplate>
                                <asp:Label ID="lblTaskId" runat="server" Text='<%# Bind("Ans_Id") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        

                        <%--Employee Name--%>
                        <asp:TemplateField HeaderStyle-BorderStyle="None" HeaderText="From" >
                            <HeaderStyle BorderStyle="None" />
                            <ItemStyle CssClass="TableRowCss" />
                            <FooterStyle CssClass="FooterRowCss"></FooterStyle>

                            <ItemTemplate>
                                <asp:Label ID="lblEmpName" runat="server" ></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        
                        <%-- Response Date --%>
                                                <asp:TemplateField HeaderStyle-BorderStyle="None" HeaderText="" >
                            <HeaderStyle BorderStyle="None" />
                            <ItemStyle CssClass="TableRowCss DescriptionFieldCss" />
                            <FooterStyle CssClass="FooterRowCss"></FooterStyle>

                            <ItemTemplate>
                                <asp:Label ID="lblResponseDate" CssClass="CenterCss" runat="server"></asp:Label>
                            </ItemTemplate>

                        </asp:TemplateField>

                        <%-- Response --%>
                        <asp:TemplateField HeaderStyle-BorderStyle="None" HeaderText="Response" >
                            <HeaderStyle BorderStyle="None" />
                            <ItemStyle CssClass="TableRowCss DescriptionFieldCss" />
                            <FooterStyle CssClass="FooterRowCss"></FooterStyle>

                            <ItemTemplate>
                                <asp:Label ID="lblResponse" runat="server"  Width="400" Text='<%# Bind("Response") %>'></asp:Label>
                            </ItemTemplate>

                        </asp:TemplateField>
                        
                        
                         <%--Score --%>
                        <asp:TemplateField HeaderStyle-BorderStyle="None" HeaderText="Score" >
                            <HeaderStyle BorderStyle="None" />
                            <ItemStyle CssClass="TableRowCss" />
                            <FooterStyle CssClass="FooterRowCss"></FooterStyle>

                            <ItemTemplate>
                                <asp:Label ID="lblScore" runat="server" Text='<%# Bind("Score") %>'></asp:Label>
                                
                                <asp:LinkButton ID="BtnScore" Runat="server" CausesValidation="False" CommandName="Edit">
                                    <img src="/Images/Score.png" alt="Score" style="border: 0; height: 32px; width: 32px; margin-right: 0; margin-left: 5px; margin-top: 0; float: right; "/>
                                </asp:LinkButton>
                                <asp:TextBox runat="server"  ID="NewScore" MaxLength="3" CssClass="ScoreCss" ></asp:TextBox>
                                
                            </ItemTemplate>
                             

                         </asp:TemplateField>
                    </Columns>

                    <PagerStyle HorizontalAlign="Left"/>
                </SIU:SelfSortingGrid>
                
                <div style=" text-align: center;">
                    <asp:Label runat="server"  ID="LblBadNameError"  CssClass="LblBadNameErrorCss" BorderWidth="0"></asp:Label>
                </div>
            </div>
            
        </asp:Panel> 
    </div>            
            
    <asp:ObjectDataSource ID="OdsSelect"    runat="server" TypeName="SqlServer_Impl" SelectMethod="GetSafetyQomQOpenList"></asp:ObjectDataSource>
    <asp:ObjectDataSource ID="OdsPoints"      runat="server" TypeName="SqlServer_Impl" SelectMethod="GetSafetyQomRList" >
        <SelectParameters>
            <asp:ControlParameter ControlID="gvSafetyQomAnsAdminSelect" Name="QID" Type="Int32"/>
        </SelectParameters>
    </asp:ObjectDataSource>  

</asp:Content>

