<%@ Page Title="" Language="C#" MasterPageFile="~/SiteMaster2.master" AutoEventWireup="true" CodeFile="SafetyQoMAdmin.aspx.cs" Inherits="Forms_SafetyQoMAdmin" %>
<%@ Register TagPrefix="asp" Namespace="AjaxControlToolkit" Assembly="AjaxControlToolkit, Version=4.1.60623.0, Culture=neutral, PublicKeyToken=28f01b0e84b6d53e" %>

<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" Runat="Server">
 
    <script type="text/javascript">
        $(document).ready(function () {

            var refTaskDefinition = $("#Question");

            refTaskDefinition.blur(function () {
                refTaskDefinition.height(18);
            });

            refTaskDefinition.focus(function () {
                refTaskDefinition.height(200);
            });



            $('#StartDate').datepicker();
            $('#EndDate').datepicker({
                minDate: $('#StartDate')[0].innerHTML
            });            
        })
    </script> 
    
    <style>
        .QuestionInputCSS {
            Width: 300px;
            Height: 18px;
        }
        
        .LblBadNameErrorCss {
            font-size: 1.5em;
            text-align: center;
            font-style: italic;
            color: red;
            background-color: yellow;
            border: 2px solid red;
        }       
        
    
          
    </style>
</asp:Content>


<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" Runat="Server">
    <asp:ToolkitScriptManager ID="ToolkitScriptManager1" runat="Server" />
    
<!----------------->
<!-- Form Header -->
<!----------------->           
    <div class="ui-widget-header ui-corner-all"  >
        <div  style="text-align: center; font-size: 2em;">Safety Question Definition</div>
    </div>   
    
    <div class="ui-widget-content ui-corner-all">                 
        <asp:Panel ID="pnlGridView" runat="server">
        
            <div style="height: 65px; padding-top: 10px;"></div>    

            <div style="margin-left: auto; margin-right: auto; width:600px;">
                <SIU:SelfSortingGrid ID="gvSafetyQoMList" runat="server" CssClass="GridCenterCss"
                    
                    AutoGenerateColumns="False" 
                    AutoGenerateSelectButton="False" 
                    AutoGenerateEditButton="False"
                    AutoGenerateDeleteButton="False"
                     
                    AllowSorting="True"
                    AllowPaging="True" 

                    ShowFooter="True"
                    
                    
                    PageSize="10" 
                    CellPadding="2" 
                    CellSpacing="2" 

                    BorderStyle="None"
                                     
                    OnRowEditing="gvSafetyQoMList_RowEditing" 
                    OnSelectedIndexChanged="gvSafetyQoMList_SelectedIndexChanged" 
                                    
                    OnPageIndexChanging="gvSafetyQoMList_PageIndexChanging" 
                    OnSorting="gvSafetyQoMList_Sorting" 
                    OnRowDataBound="gvSafetyQoMList_RowDataBound"
                 >
                                    
                    <RowStyle CssClass="TableRowCss"></RowStyle>
                    

                    <AlternatingRowStyle BackColor="#333333" />
                    <Columns>
                        
                        <%-- Question ID --%>
                        <asp:TemplateField HeaderStyle-BorderStyle="None" HeaderText="Task" >
                            <HeaderStyle BorderStyle="None" />
                            <ItemStyle CssClass="TableRowCss" HorizontalAlign="Center" />
                            <FooterStyle BorderStyle="None"></FooterStyle>

                            <ItemTemplate>
                                <asp:Label ID="lblQId" runat="server" Text='<%# Bind("Q_Id") %>'></asp:Label>
                            </ItemTemplate>

                            <FooterTemplate>
				                <div style="color: yellow; font-weight: bold; font-style: italic; padding-left: 12px;">New<br/>Question</div>
                            </FooterTemplate>
                        </asp:TemplateField>
                        

                        <%-- Start Date --%>
                        <asp:TemplateField HeaderStyle-BorderStyle="None" HeaderText="Start Date" >
                            <HeaderStyle BorderStyle="None" />
                            <ItemStyle CssClass="TableRowCss" />
                            <FooterStyle CssClass="FooterRowCss"></FooterStyle>

                            <ItemTemplate>
                                <asp:Label ID="lblStartDate" runat="server" ></asp:Label>
                            </ItemTemplate>

				                
                                
                            <FooterTemplate>
				                <asp:TextBox ID="StartDate" runat="server" Text='<%# Bind("StartDate") %>' MaxLength="10" Width="70" CssClass="DataInputCss"  />
<%--                            
                                    <asp:CalendarExtender ID="CalendarExtender1" runat="server"
                                        TargetControlID="StartDate"
                                        Format="MM/dd/yyyy"
                                        PopupPosition="BottomLeft" />
                                        --%>
                                    <asp:RequiredFieldValidator
                                        ID="RfvStartDate" runat="server" ErrorMessage="Define A Start Date" ControlToValidate="StartDate">&nbsp;
                                    </asp:RequiredFieldValidator>

                                        <ajaxToolkit:ValidatorCalloutExtender 
                                            runat="Server" ID="ExtRfvStartDate" TargetControlID="RfvStartDate" Width="250px"
                                            HighlightCssClass="highlight" CssClass="CustomValidatorCalloutStyle" PopupPosition="TopLeft"
                                            WarningIconImageUrl="/Images/warning.gif" CloseImageUrl="/Images//close.png" />
                                        
                                    <asp:RegularExpressionValidator ID="RevStartDate" runat="server" ErrorMessage="Enter A Date using MM/DD/YYYY format" 
                                    ValidationExpression="^(((0?[1-9]|1[012])/(0?[1-9]|1\d|2[0-8])|(0?[13456789]|1[012])/(29|30)|(0?[13578]|1[02])/31)/(19|[2-9]\d)\d{2}|0?2/29/((19|[2-9]\d)(0[48]|[2468][048]|[13579][26])|(([2468][048]|[3579][26])00)))$" 
                                    ControlToValidate="StartDate">&nbsp;
                                    </asp:RegularExpressionValidator>  
                                    
                                        <ajaxToolkit:ValidatorCalloutExtender 
                                            runat="Server" ID="ExtRevStartDate" TargetControlID="RevStartDate" Width="250px"
                                            HighlightCssClass="highlight" CssClass="CustomValidatorCalloutStyle" PopupPosition="TopRight"
                                            WarningIconImageUrl="/Images/warning.gif" CloseImageUrl="/Images//close.png" />                                      

                            </FooterTemplate>

                        </asp:TemplateField>
                        
                        

                        <%-- End Date --%>
                        <asp:TemplateField HeaderStyle-BorderStyle="None" HeaderText="End Date" >
                            <HeaderStyle BorderStyle="None" />
                            <ItemStyle CssClass="TableRowCss" />
                            <FooterStyle CssClass="FooterRowCss"></FooterStyle>

                            <ItemTemplate>
                                <asp:Label ID="lblEndDate" runat="server" ></asp:Label>
                            </ItemTemplate>

				                
                                
                            <FooterTemplate>
				                <asp:TextBox ID="EndDate" runat="server" Text='<%# Bind("EndDate") %>' MaxLength="10" Width="70" CssClass="DataInputCss"  />
<%--                            
                                    <asp:CalendarExtender ID="CalendarExtender2" runat="server"
                                        TargetControlID="EndDate"
                                        Format="MM/dd/yyyy"
                                        PopupPosition="BottomLeft" />
                                        --%>
                                    <asp:RequiredFieldValidator
                                        ID="RfvEndDate" runat="server" ErrorMessage="Define An End Date" ControlToValidate="EndDate">&nbsp;
                                    </asp:RequiredFieldValidator>

                                        <ajaxToolkit:ValidatorCalloutExtender 
                                            runat="Server" ID="ExtRfvEndDate" TargetControlID="RfvEndDate" Width="250px"
                                            HighlightCssClass="highlight" CssClass="CustomValidatorCalloutStyle" PopupPosition="TopRight"
                                            WarningIconImageUrl="/Images/warning.gif" CloseImageUrl="/Images//close.png" />
                                        
                                    <asp:RegularExpressionValidator ID="RevEndDate" runat="server" ErrorMessage="Enter A Date using MM/DD/YYYY format" 
                                    ValidationExpression="^(((0?[1-9]|1[012])/(0?[1-9]|1\d|2[0-8])|(0?[13456789]|1[012])/(29|30)|(0?[13578]|1[02])/31)/(19|[2-9]\d)\d{2}|0?2/29/((19|[2-9]\d)(0[48]|[2468][048]|[13579][26])|(([2468][048]|[3579][26])00)))$" 
                                    ControlToValidate="EndDate">&nbsp;
                                    </asp:RegularExpressionValidator>  
                                    
                                        <ajaxToolkit:ValidatorCalloutExtender 
                                            runat="Server" ID="ExtRevEndDate" TargetControlID="RevEndDate" Width="250px"
                                            HighlightCssClass="highlight" CssClass="CustomValidatorCalloutStyle" PopupPosition="TopRight"
                                            WarningIconImageUrl="/Images/warning.gif" CloseImageUrl="/Images//close.png" />                                      

                            </FooterTemplate>

                        </asp:TemplateField>                      
                        
                        

                        

                        <%-- Question --%>
                        <asp:TemplateField HeaderStyle-BorderStyle="None" HeaderText="Description" >
                            <HeaderStyle BorderStyle="None" />
                            <ItemStyle CssClass="TableRowCss DescriptionFieldCss" />
                            <FooterStyle CssClass="FooterRowCss"></FooterStyle>

                            <ItemTemplate>
                                <asp:Label ID="lblTaskQ" runat="server" Text='<%# Bind("Question") %>' Width="300"></asp:Label>
                            </ItemTemplate>

                            <FooterTemplate>
				                <asp:TextBox ID="Question" runat="server" Text='<%# Bind("Question") %>' TextMode="MultiLine" MaxLength="1000" CssClass="DataInputCss QuestionInputCSS"  />
                                
                                    <asp:RequiredFieldValidator
                                        ID="RfvQomQ" runat="server" ErrorMessage="Provide A Question" ControlToValidate="Question" >&nbsp;
                                    </asp:RequiredFieldValidator>

                                    <ajaxToolkit:ValidatorCalloutExtender 
                                        runat="Server" ID="ExtRfvQomQ" TargetControlID="RfvQomQ" Width="250px"
                                        HighlightCssClass="highlight" CssClass="CustomValidatorCalloutStyle" PopupPosition="TopRight"
                                        WarningIconImageUrl="/Images/warning.gif" CloseImageUrl="/Images//close.png" />
                                        

                            </FooterTemplate>
                        </asp:TemplateField>

                    </Columns>

                    <PagerStyle HorizontalAlign="Left"/>
                </SIU:SelfSortingGrid>
                
                <div >
                    <asp:Button ID="btnNew" runat="server"  Text="Add" OnClick="NewBtn_OnClick" CssClass="NewBtnCSS"/>
                </div>
                
                <div style=" text-align: center;">
                    <asp:Label runat="server"  ID="LblOverLappingDates"  CssClass="LblBadNameErrorCss" BorderWidth="0"></asp:Label>
                </div>
            </div>
        </asp:Panel> 
    </div>     
</asp:Content>

